import{createHash}from"node:crypto";import type{TenantQueryClient}from"../database/tenant-transaction.js";
export interface WeeklyShiftSlot{weekday:number;start:string;end:string}export interface ClosedShiftException{date:string;type:"CLOSED"}export interface ReplaceShiftException{date:string;type:"REPLACE";slots:{start:string;end:string}[]}export type ShiftException=ClosedShiftException|ReplaceShiftException;
export interface UnitShiftSchedule{unitId:string;userId:string;version:number;effectiveFrom:string;timeZone:string;weeklySlots:WeeklyShiftSlot[];exceptions:ShiftException[];updatedAt:Date;replayed?:boolean}
export interface UnitShiftMember{userId:string;displayName:string;role:"TENANT_ADMIN"|"UNIT_MANAGER"|"SUPERVISOR"|"ATTENDANT"}
export interface SetUnitShiftScheduleInput{unitId:string;userId:string;effectiveFrom:string;weeklySlots:WeeklyShiftSlot[];exceptions:ShiftException[];expectedVersion:number;idempotencyKey:string}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,DATE=/^\d{4}-\d{2}-\d{2}$/,TIME=/^(?:[01]\d|2[0-3]):[0-5]\d$/;
function validDate(value:string){if(!DATE.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return!Number.isNaN(date.valueOf())&&date.toISOString().slice(0,10)===value}
function normalize(input:Omit<SetUnitShiftScheduleInput,"idempotencyKey">){if(!input||typeof input!=="object"||typeof input.unitId!=="string"||typeof input.userId!=="string"||typeof input.effectiveFrom!=="string")throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");const unitId=input.unitId.trim().toLowerCase(),userId=input.userId.trim().toLowerCase();
 if(!UUID.test(unitId)||!UUID.test(userId)||!validDate(input.effectiveFrom)||!Number.isInteger(input.expectedVersion)||input.expectedVersion<0||!Array.isArray(input.weeklySlots)||input.weeklySlots.length>28||!Array.isArray(input.exceptions)||input.exceptions.length>90)throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 if(input.weeklySlots.some(slot=>!slot||typeof slot!=="object"||typeof slot.weekday!=="number"||typeof slot.start!=="string"||typeof slot.end!=="string"))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 const weeklySlots=input.weeklySlots.map(slot=>({end:slot.end,start:slot.start,weekday:slot.weekday})).sort((a,b)=>a.weekday-b.weekday||a.start.localeCompare(b.start)||a.end.localeCompare(b.end));
 if(weeklySlots.some(slot=>!Number.isInteger(slot.weekday)||slot.weekday<1||slot.weekday>7||!TIME.test(slot.start)||!TIME.test(slot.end)||slot.start>=slot.end))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 for(let i=0;i<weeklySlots.length;i++){const slot=weeklySlots[i]!,previous=weeklySlots[i-1];if(previous&&previous.weekday===slot.weekday&&previous.end>slot.start)throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST")}
 if([...new Set(weeklySlots.map(slot=>slot.weekday))].some(day=>weeklySlots.filter(slot=>slot.weekday===day).length>4))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 if(input.exceptions.some(exception=>!exception||typeof exception!=="object"||typeof exception.date!=="string"||(exception.type!=="CLOSED"&&exception.type!=="REPLACE")||(exception.type==="REPLACE"&&(!Array.isArray(exception.slots)||exception.slots.some(slot=>!slot||typeof slot!=="object"||typeof slot.start!=="string"||typeof slot.end!=="string")))))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 const exceptions=input.exceptions.map(exception=>exception.type==="CLOSED"?{date:exception.date,type:"CLOSED"as const}:{date:exception.date,type:"REPLACE"as const,slots:exception.slots.map(slot=>({end:slot.end,start:slot.start})).sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end))}).sort((a,b)=>a.date.localeCompare(b.date));
 if(exceptions.some((exception,index)=>!validDate(exception.date)||(index>0&&exceptions[index-1]!.date===exception.date)||exception.type==="REPLACE"&&(exception.slots.length<1||exception.slots.length>4||exception.slots.some((slot,i)=>!TIME.test(slot.start)||!TIME.test(slot.end)||slot.start>=slot.end||(i>0&&exception.slots[i-1]!.end>slot.start)))))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");
 return{unitId,userId,effectiveFrom:input.effectiveFrom,weeklySlots,exceptions,expectedVersion:input.expectedVersion}}
export function shiftScheduleFingerprint(input:Omit<SetUnitShiftScheduleInput,"idempotencyKey">){return createHash("sha256").update(JSON.stringify(normalize(input))).digest("hex")}
export async function getUnitShiftSchedule(client:TenantQueryClient,unitId:string,userId:string):Promise<UnitShiftSchedule>{const u=unitId.trim().toLowerCase(),a=userId.trim().toLowerCase();if(!UUID.test(u)||!UUID.test(a))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");const result=await client.query(`SELECT unit_id AS "unitId",user_id AS "userId",version,effective_from::text AS "effectiveFrom",time_zone AS "timeZone",weekly_slots AS "weeklySlots",exceptions,updated_at AS "updatedAt" FROM get_unit_shift_schedule($1,$2)`,[u,a])as{rows:UnitShiftSchedule[]};if(result.rows.length!==1)throw new Error("SHIFT_SCHEDULE_NOT_FOUND");return result.rows[0]!}
export async function listUnitShiftMembers(client:TenantQueryClient,unitId:string):Promise<UnitShiftMember[]>{const normalized=unitId.trim().toLowerCase();if(!UUID.test(normalized))throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");const result=await client.query(`SELECT user_id AS "userId",display_name AS "displayName",role FROM list_unit_shift_members($1)`,[normalized])as{rows:UnitShiftMember[]};return result.rows}
export async function setUnitShiftSchedule(client:TenantQueryClient,input:SetUnitShiftScheduleInput):Promise<UnitShiftSchedule>{const normalized=normalize(input),key=input.idempotencyKey;if(key.trim()!==key||key.length<8||key.length>200)throw new Error("INVALID_SHIFT_SCHEDULE_REQUEST");const fingerprint=shiftScheduleFingerprint(normalized),result=await client.query(`SELECT unit_id AS "unitId",user_id AS "userId",version,effective_from::text AS "effectiveFrom",time_zone AS "timeZone",weekly_slots AS "weeklySlots",exceptions,updated_at AS "updatedAt",replayed FROM set_unit_shift_schedule($1,$2,$3::date,$4::jsonb,$5::jsonb,$6,$7,$8)`,[normalized.unitId,normalized.userId,normalized.effectiveFrom,JSON.stringify(normalized.weeklySlots),JSON.stringify(normalized.exceptions),normalized.expectedVersion,key,fingerprint])as{rows:UnitShiftSchedule[]};if(result.rows.length!==1)throw new Error("SHIFT_SCHEDULE_NOT_FOUND");return result.rows[0]!}
export type EffectiveStaffShiftState="IN_SHIFT"|"OUTSIDE_SHIFT"|"CLOSED"|"NOT_EFFECTIVE"|"UNCONFIGURED";
export interface EffectiveUnitStaffShift{unitId:string;userId:string;state:EffectiveStaffShiftState;scheduleVersion:number|null;effectiveFrom:string|null;timeZone:string|null;localDate:string|null;localTime:string|null}
export async function evaluateUnitStaffShift(client:TenantQueryClient,input:{unitId:string;userId:string;at?:Date}):Promise<EffectiveUnitStaffShift>{const unitId=input.unitId?.trim().toLowerCase(),userId=input.userId?.trim().toLowerCase();
 if(!UUID.test(unitId)||!UUID.test(userId)||input.at!==undefined&&(!(input.at instanceof Date)||!Number.isFinite(input.at.getTime())))throw new Error("INVALID_SHIFT_EVALUATION_REQUEST");
 const result=await client.query(`SELECT unit_id AS "unitId",user_id AS "userId",state,schedule_version AS "scheduleVersion",effective_from::text AS "effectiveFrom",time_zone AS "timeZone",local_date::text AS "localDate",local_time AS "localTime" FROM evaluate_unit_staff_shift($1,$2,$3::timestamptz)`,[unitId,userId,input.at?.toISOString()??null])as{rows:EffectiveUnitStaffShift[]};if(result.rows.length!==1)throw new Error("SHIFT_EVALUATION_NOT_FOUND");return result.rows[0]!}
