// @vitest-environment jsdom
import{cleanup,fireEvent,render,screen,waitFor}from"@testing-library/react";import{afterEach,describe,expect,it,vi}from"vitest";import{ApiProblem}from"@zap-pronto/api-client";import{TeamAvailabilityPanel,type TeamAvailabilityClient}from"./TeamAvailabilityPanel.js";
const units=[{id:"33333333-3333-4333-8333-333333333333",name:"Centro"},{id:"44444444-4444-4444-8444-444444444444",name:"Norte"}],item={userId:"22222222-2222-4222-8222-222222222222",displayName:"Ana",role:"ATTENDANT",status:"AVAILABLE"as const,maxActive:4,activeCount:1,remainingCapacity:3,pauseReason:null,pausedUntil:null,updatedAt:"2026-08-13T10:00:00.000Z"};
const client=(list:TeamAvailabilityClient["listInboxTeamAvailability"]):TeamAvailabilityClient=>({listInboxTeamAvailability:list});afterEach(cleanup);
describe("disponibilidade da equipe",()=>{
 it("não repete a leitura quando o shell recria a mesma lista de unidades",async()=>{const list=vi.fn(async()=>({items:[item]})),stableClient=client(list);const view=render(<TeamAvailabilityPanel client={stableClient} authorizedUnits={units}/>);await screen.findByText("Ana");view.rerender(<TeamAvailabilityPanel client={stableClient} authorizedUnits={units.map(unit=>({...unit}))}/>);await waitFor(()=>expect(list).toHaveBeenCalledTimes(1))});
 it("carrega somente ao montar e aplica filtro sem polling",async()=>{const list=vi.fn(async()=>({items:[item]}));render(<TeamAvailabilityPanel client={client(list)} authorizedUnits={units}/>);expect(await screen.findByText("Ana")).toBeTruthy();expect(list).toHaveBeenCalledTimes(1);fireEvent.change(screen.getByLabelText("Status"),{target:{value:"PAUSED"}});await waitFor(()=>expect(list).toHaveBeenLastCalledWith({unitId:units[0]!.id,limit:25,status:"PAUSED"}));expect(list).toHaveBeenCalledTimes(2)});
 it("pagina com cursor e deduplica usuário mantendo a página mais recente",async()=>{const updated={...item,activeCount:2,remainingCapacity:2};const list=vi.fn().mockResolvedValueOnce({items:[item],nextCursor:"next"}).mockResolvedValueOnce({items:[updated]});render(<TeamAvailabilityPanel client={client(list)} authorizedUnits={units}/>);await screen.findByText("Capacidade: 1/4 · Restante: 3");fireEvent.click(screen.getByRole("button",{name:"Carregar mais"}));expect(await screen.findByText("Capacidade: 2/4 · Restante: 2")).toBeTruthy();expect(screen.queryByText("Capacidade: 1/4 · Restante: 3")).toBeNull();expect(list).toHaveBeenLastCalledWith({unitId:units[0]!.id,limit:25,cursor:"next"})});
 it("ignora resposta antiga após troca de unidade",async()=>{let release!:(value:{items:typeof item[]})=>void;const first=new Promise<{items:typeof item[]}>(resolve=>{release=resolve});const list=vi.fn().mockReturnValueOnce(first).mockResolvedValueOnce({items:[{...item,userId:"55555555-5555-4555-8555-555555555555",displayName:"Bia"}]});render(<TeamAvailabilityPanel client={client(list)} authorizedUnits={units}/>);fireEvent.change(screen.getByLabelText("Unidade"),{target:{value:units[1]!.id}});expect(await screen.findByText("Bia")).toBeTruthy();release({items:[item]});await waitFor(()=>expect(screen.queryByText("Ana")).toBeNull())});
 it.each([401,403])("purga dados e encaminha acesso %i",async status=>{const callback=vi.fn(),list=vi.fn().mockResolvedValueOnce({items:[item]}).mockRejectedValueOnce(new ApiProblem({type:"urn:test",title:"private",status,correlationId:"secret"}));render(<TeamAvailabilityPanel client={client(list)} authorizedUnits={units} {...(status===401?{onAuthenticationRequired:callback}:{onAuthorizationChanged:callback})}/>);await screen.findByText("Ana");fireEvent.click(screen.getByRole("button",{name:"Atualizar equipe"}));await waitFor(()=>expect(callback).toHaveBeenCalledOnce());expect(screen.queryByText("Ana")).toBeNull();expect(document.body.textContent).not.toContain("secret")});
});
