import{useEffect,useRef,useState}from"react";import{ApiProblem,AuthenticationRequired}from"@zap-pronto/api-client";
export type TeamAvailabilityStatus="AVAILABLE"|"PAUSED"|"OFFLINE";
export type TeamAvailabilityItem={readonly userId:string;readonly displayName:string;readonly role:string;readonly status:TeamAvailabilityStatus;readonly maxActive:number;readonly activeCount:number;readonly remainingCapacity:number;readonly pauseReason:string|null;readonly pausedUntil:string|null;readonly updatedAt:string};
export interface TeamAvailabilityClient{listInboxTeamAvailability(input:{unitId:string;limit?:number;status?:TeamAvailabilityStatus;cursor?:string}):Promise<{items:readonly TeamAvailabilityItem[];nextCursor?:string}>}
export type TeamAvailabilityUnit={readonly id:string;readonly name:string};
const statusLabel={AVAILABLE:"Disponível",PAUSED:"Pausado",OFFLINE:"Offline"}satisfies Record<TeamAvailabilityStatus,string>;
export function TeamAvailabilityPanel({client,authorizedUnits,onAuthenticationRequired=()=>undefined,onAuthorizationChanged=()=>undefined}:{readonly client:TeamAvailabilityClient;readonly authorizedUnits:readonly TeamAvailabilityUnit[];readonly onAuthenticationRequired?:()=>void;readonly onAuthorizationChanged?:()=>void}){
 const[unitId,setUnitId]=useState(authorizedUnits[0]?.id??"");const[status,setStatus]=useState<TeamAvailabilityStatus|"">("");const[items,setItems]=useState<readonly TeamAvailabilityItem[]>([]);const[cursor,setCursor]=useState<string>();const[loading,setLoading]=useState(Boolean(unitId));const[error,setError]=useState<string>();const generation=useRef(0);
 const authorizedUnitIds=authorizedUnits.map(unit=>unit.id).join(",");
 function purge(){generation.current+=1;setItems([]);setCursor(undefined);setLoading(false);setError(undefined)}
 function accessFailure(cause:unknown){if(cause instanceof AuthenticationRequired||cause instanceof ApiProblem&&cause.problem.status===401){purge();onAuthenticationRequired();return true}if(cause instanceof ApiProblem&&cause.problem.status===403){purge();onAuthorizationChanged();return true}return false}
 async function load({append=false,nextCursor}:{append?:boolean;nextCursor?:string}={}){if(!authorizedUnits.some(unit=>unit.id===unitId))return;const g=++generation.current,captured=unitId;setLoading(true);setError(undefined);try{const page=await client.listInboxTeamAvailability({unitId:captured,limit:25,...(status?{status}:{}),...(nextCursor?{cursor:nextCursor}:{})});if(g!==generation.current||captured!==unitId)return;setItems(current=>{const merged=append?[...current,...page.items]:[...page.items];return[...new Map(merged.map(item=>[item.userId,item])).values()]});setCursor(page.nextCursor)}catch(cause){if(g!==generation.current)return;if(!accessFailure(cause))setError("Não foi possível carregar a disponibilidade da equipe.")}finally{if(g===generation.current)setLoading(false)}}
 useEffect(()=>{if(!unitId||!authorizedUnits.some(unit=>unit.id===unitId)){const fallback=authorizedUnits[0]?.id??"";purge();setUnitId(fallback);setLoading(Boolean(fallback));return}void load();return()=>{generation.current+=1}},[client,unitId,status,authorizedUnitIds]);
 return <section aria-labelledby="team-availability-title"><h2 id="team-availability-title">Disponibilidade da equipe</h2>{authorizedUnits.length===0?<p>Nenhuma unidade autorizada.</p>:<><label>Unidade<select value={unitId} disabled={loading} onChange={event=>{purge();setUnitId(event.target.value)}}>{authorizedUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label>Status<select value={status} disabled={loading} onChange={event=>{purge();setStatus(event.target.value as TeamAvailabilityStatus|"")}}><option value="">Todos</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="button" disabled={loading} onClick={()=>void load()}>Atualizar equipe</button></>}{loading&&items.length===0?<p>Carregando…</p>:error?<><p role="alert">{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></>:items.length===0?<p>Nenhum integrante encontrado.</p>:<ul>{items.map(item=><li key={item.userId}><strong>{item.displayName}</strong><span>{item.role} · {statusLabel[item.status]}</span><span>Capacidade: {item.activeCount}/{item.maxActive} · Restante: {item.remainingCapacity}</span>{item.pauseReason&&<span>Motivo: {item.pauseReason}</span>}</li>)}</ul>}{cursor&&<button type="button" disabled={loading} onClick={()=>void load({append:true,nextCursor:cursor})}>Carregar mais</button>}</section>
}
