// @vitest-environment jsdom
import{cleanup,fireEvent,render,screen,waitFor}from"@testing-library/react";import{afterEach,describe,expect,it,vi}from"vitest";import{ApiProblem}from"@zap-pronto/api-client";import{UnitOperationalTimezonePanel as Panel,type UnitOperationalTimezone,type UnitOperationalTimezoneClient}from"./UnitOperationalTimezonePanel.js";
const unitId="33333333-3333-4333-8333-333333333333",units=[{id:unitId,name:"Centro"},{id:"44444444-4444-4444-8444-444444444444",name:"Norte"}],configuration:UnitOperationalTimezone={unitId,timeZone:"America/Sao_Paulo",version:2,updatedAt:"2026-08-13T12:00:00.000Z"};
function client(overrides:Partial<UnitOperationalTimezoneClient>={}):UnitOperationalTimezoneClient{return{getUnitOperationalTimezone:async()=>configuration,setUnitOperationalTimezone:async(_unit,input)=>({...configuration,...input,version:input.expectedVersion+1}),...overrides}}
afterEach(cleanup);describe("fuso operacional da unidade",()=>{
 it("mantém ausência neutra sem presumir timezone",async()=>{render(<Panel client={client({getUnitOperationalTimezone:async()=>null})} readableUnits={units} manageableUnitIds={[unitId]}/>);expect(await screen.findByText("Nenhum fuso operacional configurado para esta unidade.")).toBeTruthy();expect((screen.getByLabelText("Fuso IANA")as HTMLInputElement).value).toBe("");expect(screen.getByRole("button",{name:"Salvar fuso operacional"}).hasAttribute("disabled")).toBe(true)});
 it("aceita identificadores IANA válidos sem barra e deixa a existência para o servidor",async()=>{render(<Panel client={client({getUnitOperationalTimezone:async()=>null})} readableUnits={units} manageableUnitIds={[unitId]}/>);await screen.findByText("Nenhum fuso operacional configurado para esta unidade.");fireEvent.change(screen.getByLabelText("Fuso IANA"),{target:{value:"UTC"}});expect(screen.getByRole("button",{name:"Salvar fuso operacional"}).hasAttribute("disabled")).toBe(false)});
 it("expõe leitura ao supervisor sem editor",async()=>{const set=vi.fn();render(<Panel client={client({setUnitOperationalTimezone:set})} readableUnits={units} manageableUnitIds={[]}/>);expect(await screen.findByText(/Fuso vigente: America\/Sao_Paulo/)).toBeTruthy();expect(screen.getByText("America/Sao_Paulo")).toBeTruthy();expect(screen.queryByLabelText("Fuso IANA")).toBeNull();expect(set).not.toHaveBeenCalled()});
 it("confirma, trava duplo envio e reutiliza a chave no retry",async()=>{const set=vi.fn().mockRejectedValueOnce(new Error("private")).mockResolvedValueOnce({...configuration,timeZone:"America/Manaus",version:3});render(<Panel client={client({setUnitOperationalTimezone:set})} readableUnits={units} manageableUnitIds={[unitId]}/>);await screen.findByText(/Versão 2/);fireEvent.change(screen.getByLabelText("Fuso IANA"),{target:{value:"America/Manaus"}});fireEvent.click(screen.getByRole("button",{name:"Salvar fuso operacional"}));expect(screen.getByText(/não modifica atendimentos nem claims/)).toBeTruthy();const confirm=screen.getByRole("button",{name:"Confirmar alteração"});fireEvent.click(confirm);fireEvent.click(confirm);await screen.findByRole("alert");expect(set).toHaveBeenCalledTimes(1);const key=set.mock.calls[0]?.[2];fireEvent.click(confirm);expect(await screen.findByText("Fuso operacional atualizado.")).toBeTruthy();expect(set).toHaveBeenCalledTimes(2);expect(set.mock.calls[1]?.[2]).toBe(key);expect(set.mock.calls[1]?.[1]).toEqual({expectedVersion:2,timeZone:"America/Manaus"})});
 it.each([404,409])("refaz GET depois de %i sem conservar intenção obsoleta",async status=>{const get=vi.fn().mockResolvedValueOnce(configuration).mockResolvedValueOnce({...configuration,version:4});render(<Panel client={client({getUnitOperationalTimezone:get,setUnitOperationalTimezone:async()=>{throw new ApiProblem({type:"urn:test",title:"private",status,correlationId:"secret"})}})} readableUnits={units} manageableUnitIds={[unitId]}/>);await screen.findByText(/Versão 2/);fireEvent.change(screen.getByLabelText("Fuso IANA"),{target:{value:"America/Manaus"}});fireEvent.click(screen.getByRole("button",{name:"Salvar fuso operacional"}));fireEvent.click(screen.getByRole("button",{name:"Confirmar alteração"}));await waitFor(()=>expect(get).toHaveBeenCalledTimes(2));expect(screen.queryByRole("dialog")).toBeNull();expect(document.body.textContent).not.toContain("secret")});
 it.each([401,403])("purga dados antes do callback %i",async status=>{const callback=vi.fn();render(<Panel client={client({setUnitOperationalTimezone:async()=>{throw new ApiProblem({type:"urn:test",title:"secret",status,correlationId:"private"})}})} readableUnits={units} manageableUnitIds={[unitId]} {...(status===401?{onAuthenticationRequired:callback}:{onAuthorizationChanged:callback})}/>);await screen.findByText(/Versão 2/);fireEvent.change(screen.getByLabelText("Fuso IANA"),{target:{value:"America/Manaus"}});fireEvent.click(screen.getByRole("button",{name:"Salvar fuso operacional"}));fireEvent.click(screen.getByRole("button",{name:"Confirmar alteração"}));await waitFor(()=>expect(callback).toHaveBeenCalledOnce());expect(screen.queryByText(/Versão 2/)).toBeNull();expect(screen.queryByRole("dialog")).toBeNull();expect(document.body.textContent).not.toContain("private")});
 it("ignora resposta antiga quando a autorização muda durante o GET",async()=>{let release!:(value:UnitOperationalTimezone|null)=>void;const stale=new Promise<UnitOperationalTimezone|null>(resolve=>{release=resolve});const get=vi.fn().mockReturnValueOnce(stale).mockResolvedValueOnce({...configuration,unitId:units[1]!.id,timeZone:"America/Recife",version:3}),stable=client({getUnitOperationalTimezone:get});const view=render(<Panel client={stable} readableUnits={units} manageableUnitIds={units.map(unit=>unit.id)}/>);expect(screen.getByText("Carregando…")).toBeTruthy();view.rerender(<Panel client={stable} readableUnits={[units[1]!]} manageableUnitIds={[units[1]!.id]}/>);expect(await screen.findByText(/America\/Recife/)).toBeTruthy();release({...configuration,timeZone:"America/Manaus",version:9});await waitFor(()=>expect(screen.queryByText(/Versão 9/)).toBeNull())});
 it("protege troca de unidade com formulário sujo",async()=>{render(<Panel client={client()} readableUnits={units} manageableUnitIds={units.map(unit=>unit.id)}/>);await screen.findByText(/Versão 2/);fireEvent.change(screen.getByLabelText("Fuso IANA"),{target:{value:"America/Fortaleza"}});const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);fireEvent.change(screen.getByLabelText("Unidade"),{target:{value:units[1]!.id}});expect((screen.getByLabelText("Unidade")as HTMLSelectElement).value).toBe(unitId);expect(confirm).toHaveBeenCalledOnce()});
});
