import {useEffect,useLayoutEffect,useRef,useState}from"react";
import{ApiProblem,AuthenticationRequired}from"@zap-pronto/api-client";

export type UnitOperationalTimezone={readonly unitId:string;readonly version:number;readonly timeZone:string;readonly updatedAt:string;readonly replayed?:boolean};
export interface UnitOperationalTimezoneClient{getUnitOperationalTimezone(unitId:string):Promise<UnitOperationalTimezone|null>;setUnitOperationalTimezone(unitId:string,input:{expectedVersion:number;timeZone:string},key:string):Promise<UnitOperationalTimezone>}
export type OperationalTimezoneUnit={readonly id:string;readonly name:string};

export function UnitOperationalTimezonePanel({client,readableUnits,manageableUnitIds,onAuthenticationRequired=()=>undefined,onAuthorizationChanged=()=>undefined,onNavigationStateChange}:{readonly client:UnitOperationalTimezoneClient;readonly readableUnits:readonly OperationalTimezoneUnit[];readonly manageableUnitIds:readonly string[];readonly onAuthenticationRequired?:()=>void;readonly onAuthorizationChanged?:()=>void;readonly onNavigationStateChange?:(state:{blocked:boolean;dirty:boolean})=>void}){
 const[unitId,setUnitId]=useState(readableUnits[0]?.id??"");const[configuration,setConfiguration]=useState<UnitOperationalTimezone|null>();const[timeZone,setTimeZone]=useState("");const[loading,setLoading]=useState(readableUnits.length>0);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();const[dialogOpen,setDialogOpen]=useState(false);const[key,setKey]=useState<string>();const[submitting,setSubmitting]=useState(false);const[mutationError,setMutationError]=useState<string>();
 const generation=useRef(0),mutationLock=useRef<symbol|undefined>(undefined),dialogRef=useRef<HTMLDivElement>(null),openerRef=useRef<HTMLElement|null>(null);
 function purge(){generation.current+=1;setConfiguration(undefined);setTimeZone("");setLoading(false);setError(undefined);setNotice(undefined);setDialogOpen(false);setKey(undefined);setSubmitting(false);setMutationError(undefined);mutationLock.current=undefined}
 function accessFailure(cause:unknown){if(cause instanceof AuthenticationRequired||cause instanceof ApiProblem&&cause.problem.status===401){purge();onAuthenticationRequired();return true}if(cause instanceof ApiProblem&&cause.problem.status===403){purge();onAuthorizationChanged();return true}return false}
 function apply(value:UnitOperationalTimezone|null){setConfiguration(value);setTimeZone(value?.timeZone??"")}
 async function load(selected=unitId){if(!readableUnits.some(unit=>unit.id===selected))return;const g=++generation.current;setLoading(true);setError(undefined);setNotice(undefined);try{const value=await client.getUnitOperationalTimezone(selected);if(g!==generation.current||selected!==unitId)return;apply(value)}catch(cause){if(g!==generation.current)return;if(cause instanceof ApiProblem&&cause.problem.status===404)apply(null);else if(!accessFailure(cause))setError("Não foi possível carregar o fuso operacional.")}finally{if(g===generation.current)setLoading(false)}}
 useLayoutEffect(()=>{if(unitId&&readableUnits.some(unit=>unit.id===unitId))return;const fallback=readableUnits[0]?.id??"";purge();setLoading(Boolean(fallback));setUnitId(fallback)},[readableUnits,unitId]);
 useEffect(()=>{if(unitId&&readableUnits.some(unit=>unit.id===unitId))void load(unitId);return()=>{generation.current+=1}},[client,unitId]);
 const canManage=manageableUnitIds.includes(unitId),normalized=timeZone.trim(),valid=normalized.length>=1&&normalized.length<=100&&!/\s/u.test(normalized),dirty=canManage&&normalized!==(configuration?.timeZone??"");const blocked=dialogOpen||submitting;
 useEffect(()=>onNavigationStateChange?.({blocked,dirty:dirty||blocked||Boolean(key)}),[onNavigationStateChange,blocked,dirty,key]);useEffect(()=>()=>onNavigationStateChange?.({blocked:false,dirty:false}),[onNavigationStateChange]);
 function changeUnit(value:string){if(value===unitId||blocked)return;if(dirty&&!window.confirm("Descartar a alteração não salva do fuso operacional?"))return;purge();setLoading(true);setUnitId(value)}
 function openConfirmation(){if(!valid||!dirty)return;openerRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialogOpen(true);setMutationError(undefined);setKey(undefined)}
 function close(){if(submitting)return;setDialogOpen(false);setMutationError(undefined);setKey(undefined)}
 useEffect(()=>{if(!dialogOpen)return;dialogRef.current?.querySelector<HTMLElement>("button:not([disabled])")?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!submitting){event.preventDefault();close()}};document.addEventListener("keydown",listener);return()=>document.removeEventListener("keydown",listener)},[dialogOpen,submitting]);useEffect(()=>{if(!dialogOpen&&openerRef.current){openerRef.current.focus();openerRef.current=null}},[dialogOpen]);
 async function confirm(){if(!dialogOpen||!valid||mutationLock.current)return;const token=Symbol("operational-timezone");mutationLock.current=token;const g=generation.current,captured=unitId,retryKey=key??crypto.randomUUID();setKey(retryKey);setSubmitting(true);setMutationError(undefined);try{const value=await client.setUnitOperationalTimezone(captured,{expectedVersion:configuration?.version??0,timeZone:normalized},retryKey);if(g!==generation.current||captured!==unitId)return;apply(value);setDialogOpen(false);setKey(undefined);setNotice("Fuso operacional atualizado.")}catch(cause){if(g!==generation.current)return;if(accessFailure(cause))return;if(cause instanceof ApiProblem&&(cause.problem.status===404||cause.problem.status===409)){setDialogOpen(false);setKey(undefined);await load(captured);if(captured===unitId)setNotice(cause.problem.status===404?"A unidade ou configuração não está mais disponível. Os dados foram atualizados.":"O fuso foi alterado por outra pessoa. Os dados foram atualizados.")}else setMutationError("Não foi possível atualizar o fuso operacional. Tente novamente.")}finally{if(mutationLock.current===token)mutationLock.current=undefined;if(g===generation.current)setSubmitting(false)}}
 return <section aria-labelledby="operational-timezone-title"><div inert={dialogOpen?true:undefined} aria-hidden={dialogOpen?true:undefined}><h2 id="operational-timezone-title">Escalas</h2><h3>Fuso operacional</h3>{readableUnits.length===0?<p>Nenhuma unidade autorizada.</p>:<><label>Unidade<select value={unitId} disabled={blocked} onChange={event=>changeUnit(event.target.value)}>{readableUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><button type="button" disabled={loading||blocked} onClick={()=>void load()}>Atualizar fuso</button></>}{notice&&<p role="status">{notice}</p>}{loading?<p>Carregando…</p>:error?<><p role="alert">{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></>:unitId&&<><p>{configuration?`Fuso vigente: ${configuration.timeZone}. Versão ${configuration.version}.`:"Nenhum fuso operacional configurado para esta unidade."}</p><p>Esta configuração prepara escalas futuras e não altera atendimentos, responsáveis ou claims existentes.</p>{canManage?<><label>Fuso IANA<input type="text" autoComplete="off" placeholder="America/Sao_Paulo" value={timeZone} onChange={event=>{setTimeZone(event.target.value);setKey(undefined);setMutationError(undefined);setNotice(undefined)}}/></label><button type="button" disabled={!valid||!dirty||blocked} onClick={openConfirmation}>Salvar fuso operacional</button></>:<dl><div><dt>Fuso IANA</dt><dd>{configuration?.timeZone??"Não configurado"}</dd></div></dl>}</>}</div>{dialogOpen&&<div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="timezone-confirm-title"><h3 id="timezone-confirm-title">Confirmar fuso operacional</h3><p>Confirme {normalized} para esta unidade. A alteração não modifica atendimentos nem claims.</p>{mutationError&&<p role="alert">{mutationError}</p>}<button type="button" disabled={submitting} onClick={()=>void confirm()}>{submitting?"Salvando…":"Confirmar alteração"}</button><button type="button" disabled={submitting} onClick={close}>Cancelar</button></div>}</section>
}
