import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { ApiProblem, AuthenticationRequired } from "@zap-pronto/api-client";
import type { ChangeUnitMembershipRequest } from "@zap-pronto/contracts";

export type UnitMembership = { readonly userId:string;readonly displayName:string;readonly role:"TENANT_ADMIN"|"UNIT_MANAGER"|"SUPERVISOR"|"ATTENDANT"|"AUDITOR";readonly status:"ACTIVE"|"REVOKED";readonly version:number;readonly allowedActions:readonly ("REVOKE"|"REACTIVATE")[] };
export interface UnitMembershipClient {
  listUnitMemberships(input:{unitId:string;limit?:number;cursor?:string}):Promise<{items:readonly UnitMembership[];nextCursor?:string}>;
  changeUnitMembership(userId:string,unitId:string,input:ChangeUnitMembershipRequest,key:string):Promise<unknown>;
}
export type AuthorizedUnit={readonly id:string;readonly name:string};
type Pending={item:UnitMembership;action:"REVOKE"|"REACTIVATE"};
const labels={REVOKE:"Revogar vínculo",REACTIVATE:"Reativar vínculo"}as const;

export function UnitMembershipPanel({client,authorizedUnits,onAuthenticationRequired=()=>undefined,onAuthorizationChanged=()=>undefined,onNavigationStateChange}:{readonly client:UnitMembershipClient;readonly authorizedUnits:readonly AuthorizedUnit[];readonly onAuthenticationRequired?:()=>void;readonly onAuthorizationChanged?:()=>void;readonly onNavigationStateChange?:(state:{blocked:boolean;dirty:boolean})=>void}){
  const[unitId,setUnitId]=useState(authorizedUnits[0]?.id??"");const[items,setItems]=useState<readonly UnitMembership[]>([]);const[cursor,setCursor]=useState<string>();
  const[loading,setLoading]=useState(false);const[error,setError]=useState<string>();const[pageError,setPageError]=useState<string>();const[notice,setNotice]=useState<string>();const[pending,setPending]=useState<Pending>();const[reason,setReason]=useState("");const[key,setKey]=useState<string>();const[submitting,setSubmitting]=useState(false);const[mutationError,setMutationError]=useState<string>();
  const generation=useRef(0),listFlight=useRef(false),mutationLock=useRef<symbol|undefined>(undefined);const dialogRef=useRef<HTMLDivElement>(null),openerRef=useRef<HTMLElement|null>(null);
  function purge(){generation.current+=1;setItems([]);setCursor(undefined);setError(undefined);setPageError(undefined);setNotice(undefined);setPending(undefined);setReason("");setKey(undefined);setMutationError(undefined);setLoading(false);setSubmitting(false);listFlight.current=false;mutationLock.current=undefined}
  function handleFailure(cause:unknown){if(cause instanceof AuthenticationRequired||cause instanceof ApiProblem&&cause.problem.status===401){purge();onAuthenticationRequired();return true}if(cause instanceof ApiProblem&&cause.problem.status===403){purge();onAuthorizationChanged();return true}return false}
  async function load(selected=unitId){if(!authorizedUnits.some(unit=>unit.id===selected))return;const g=++generation.current;listFlight.current=true;setItems([]);setCursor(undefined);setError(undefined);setPageError(undefined);setLoading(true);try{const page=await client.listUnitMemberships({unitId:selected,limit:25});if(g!==generation.current)return;setItems(page.items);setCursor(page.nextCursor)}catch(cause){if(g!==generation.current)return;if(!handleFailure(cause))setError("Não foi possível carregar os vínculos da unidade.")}finally{if(g===generation.current){setLoading(false);listFlight.current=false}}}
  useLayoutEffect(()=>{if(unitId&&authorizedUnits.some(unit=>unit.id===unitId))return;purge();setUnitId(authorizedUnits[0]?.id??"")},[authorizedUnits,unitId]);
  useEffect(()=>{if(unitId&&authorizedUnits.some(unit=>unit.id===unitId))void load(unitId);return()=>{generation.current+=1}},[client,unitId]);
  async function loadMore(){if(!unitId||!cursor||listFlight.current||mutationLock.current)return;listFlight.current=true;const g=generation.current;const captured=unitId;setPageError(undefined);try{const page=await client.listUnitMemberships({unitId:captured,limit:25,cursor});if(g!==generation.current||captured!==unitId)return;setItems(old=>[...new Map([...old,...page.items].map(item=>[item.userId,item])).values()]);setCursor(page.nextCursor)}catch(cause){if(g!==generation.current)return;if(!handleFailure(cause))setPageError("Não foi possível carregar mais vínculos.")}finally{if(g===generation.current)listFlight.current=false}}
  function open(item:UnitMembership,action:Pending["action"]){openerRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setPending({item,action});setReason("");setKey(undefined);setMutationError(undefined)}
  function close(){if(submitting)return;setPending(undefined);setReason("");setKey(undefined);setMutationError(undefined)}
  useEffect(()=>{if(!pending)return;dialogRef.current?.querySelector<HTMLElement>("textarea,button:not([disabled])")?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!submitting){event.preventDefault();close()}};document.addEventListener("keydown",listener);return()=>document.removeEventListener("keydown",listener)},[pending,submitting]);
  useEffect(()=>{if(!pending&&openerRef.current){openerRef.current.focus();openerRef.current=null}},[pending]);
  async function confirm(){if(!pending||reason.trim().length<3||mutationLock.current)return;const token=Symbol();mutationLock.current=token;const g=generation.current,captured=unitId,retryKey=key??crypto.randomUUID();setKey(retryKey);setSubmitting(true);setMutationError(undefined);setNotice(undefined);try{await client.changeUnitMembership(pending.item.userId,captured,{operation:pending.action,expectedVersion:pending.item.version,reason:reason.trim()},retryKey);if(g!==generation.current||captured!==unitId)return;setPending(undefined);setKey(undefined);await load(captured)}catch(cause){if(g!==generation.current)return;if(handleFailure(cause))return;if(cause instanceof ApiProblem&&(cause.problem.status===404||cause.problem.status===409)){const message=cause.problem.status===404?"O vínculo não está mais disponível. A lista foi atualizada.":"Os dados do vínculo foram alterados. A lista foi atualizada.";setPending(undefined);setReason("");setKey(undefined);await load(captured);if(generation.current>=g&&captured===unitId)setNotice(message)}else setMutationError("Não foi possível concluir a ação.")}finally{if(mutationLock.current===token)mutationLock.current=undefined;if(captured===unitId)setSubmitting(false)}}
  const dialogOpen=Boolean(pending);
  const navigationBlocked=submitting||dialogOpen,navigationDirty=navigationBlocked||reason.length>0||Boolean(key);
  useEffect(()=>{onNavigationStateChange?.({blocked:navigationBlocked,dirty:navigationDirty})},[onNavigationStateChange,navigationBlocked,navigationDirty]);
  useEffect(()=>()=>onNavigationStateChange?.({blocked:false,dirty:false}),[onNavigationStateChange]);
  return <section aria-labelledby="unit-memberships-title"><div inert={dialogOpen?true:undefined} aria-hidden={dialogOpen?true:undefined}><h2 id="unit-memberships-title">Vínculos da unidade</h2>{authorizedUnits.length===0?<p>Nenhuma unidade autorizada.</p>:<><label>Unidade<select value={unitId} onChange={event=>setUnitId(event.target.value)}>{authorizedUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><button type="button" disabled={loading||listFlight.current||Boolean(mutationLock.current)} onClick={()=>void load()}>Atualizar vínculos</button></>}{notice&&<p role="status">{notice}</p>}{loading?<p>Carregando…</p>:error?<><p role="alert">{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></>:items.length===0&&unitId?<p>Nenhum vínculo encontrado.</p>:<ul aria-label="Vínculos da unidade">{items.map(item=><li key={item.userId} aria-label={`Vínculo de ${item.displayName}`}><strong>{item.displayName}</strong> · {item.role} · {item.status==="ACTIVE"?"Ativo":"Revogado"} {item.allowedActions.map(action=><button type="button" key={action} onClick={()=>open(item,action)}>{labels[action]}</button>)}</li>)}</ul>}{cursor&&<button type="button" onClick={()=>void loadMore()}>Carregar mais vínculos</button>}{pageError&&<p role="alert">{pageError} <button type="button" onClick={()=>void loadMore()}>Tentar novamente</button></p>}</div>
  {pending&&<div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="membership-action-title"><h3 id="membership-action-title">Confirmar {labels[pending.action].toLowerCase()}</h3><p>Alvo: <strong>{pending.item.displayName}</strong>.</p><label>Motivo<textarea required minLength={3} maxLength={500} value={reason} onChange={event=>{setReason(event.target.value);setKey(undefined);setMutationError(undefined)}}/></label>{mutationError&&<p role="alert">{mutationError}</p>}<button type="button" disabled={submitting||reason.trim().length<3} onClick={()=>void confirm()}>{submitting?"Processando…":`Confirmar ${labels[pending.action].toLowerCase()}`}</button><button type="button" disabled={submitting} onClick={close}>Cancelar</button></div>}</section>
}
