// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen}from"@testing-library/react";
import{afterEach,describe,expect,it,vi}from"vitest";
import{ApiProblem}from"@zap-pronto/api-client";
import{UnitMembershipPanel,type UnitMembershipClient,type UnitMembership}from"./UnitMembershipPanel.js";
afterEach(cleanup);
const units=[{id:"10000000-0000-4000-8000-000000000001",name:"Centro"},{id:"10000000-0000-4000-8000-000000000002",name:"Norte"}];
const member:UnitMembership={userId:"20000000-0000-4000-8000-000000000001",displayName:"Agente Um",role:"ATTENDANT",status:"ACTIVE",version:4,allowedActions:["REVOKE"]};
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r});return{promise,resolve}}
function make(overrides:Partial<UnitMembershipClient>={}):UnitMembershipClient{return{async listUnitMemberships(){return{items:[member]}},async changeUnitMembership(){return{}},...overrides}}
describe("UnitMembershipPanel",()=>{
 it("bloqueia navegação durante diálogo e limpa o estado ao desmontar",async()=>{const state=vi.fn();const view=render(<UnitMembershipPanel client={make()} authorizedUnits={units} onNavigationStateChange={state}/>);fireEvent.click(await screen.findByRole("button",{name:"Revogar vínculo"}));expect(state).toHaveBeenLastCalledWith({blocked:true,dirty:true});view.unmount();expect(state).toHaveBeenLastCalledWith({blocked:false,dirty:false})});
 it("lista somente nome e dados do vínculo para unidade autorizada",async()=>{const list=vi.fn(make().listUnitMemberships);render(<UnitMembershipPanel client={make({listUnitMemberships:list})} authorizedUnits={units}/>);expect((await screen.findByRole("listitem")).textContent).toContain("Agente Um · ATTENDANT · Ativo");expect(document.body.textContent).not.toContain("@");expect(list).toHaveBeenCalledWith({unitId:units[0]!.id,limit:25})});
 it("purga na troca de unidade e ignora resposta tardia",async()=>{const late=deferred<{items:readonly UnitMembership[]}>();const list=vi.fn().mockReturnValueOnce(late.promise).mockResolvedValueOnce({items:[{...member,userId:"2",displayName:"Norte"}]});render(<UnitMembershipPanel client={make({listUnitMemberships:list})} authorizedUnits={units}/>);fireEvent.change(screen.getByLabelText("Unidade"),{target:{value:units[1]!.id}});await vi.waitFor(()=>expect(screen.getByRole("listitem").textContent).toContain("Norte · ATTENDANT"));late.resolve({items:[member]});await vi.waitFor(()=>expect(document.body.textContent).not.toContain("Agente Um"))});
 it("deduplica paginação e aplica single-flight",async()=>{const page=deferred<{items:readonly UnitMembership[]}>();const list=vi.fn().mockResolvedValueOnce({items:[member],nextCursor:"next"}).mockReturnValueOnce(page.promise);render(<UnitMembershipPanel client={make({listUnitMemberships:list})} authorizedUnits={units}/>);const more=await screen.findByRole("button",{name:"Carregar mais vínculos"});fireEvent.click(more);fireEvent.click(more);expect(list).toHaveBeenCalledTimes(2);page.resolve({items:[member]});await vi.waitFor(()=>expect(screen.getAllByRole("listitem")).toHaveLength(1))});
 it("confirma, bloqueia clique duplo e reutiliza retry key",async()=>{const change=vi.fn().mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce({});render(<UnitMembershipPanel client={make({changeUnitMembership:change})} authorizedUnits={units}/>);fireEvent.click(await screen.findByRole("button",{name:"Revogar vínculo"}));expect(document.activeElement).toBe(screen.getByLabelText("Motivo"));fireEvent.change(screen.getByLabelText("Motivo"),{target:{value:"Mudança de equipe"}});const confirm=screen.getByRole("button",{name:"Confirmar revogar vínculo"});fireEvent.click(confirm);fireEvent.click(confirm);await screen.findByText("Não foi possível concluir a ação.");expect(change).toHaveBeenCalledTimes(1);fireEvent.click(confirm);await vi.waitFor(()=>expect(change).toHaveBeenCalledTimes(2));expect(change.mock.calls[0]?.[2]).toEqual({operation:"REVOKE",expectedVersion:4,reason:"Mudança de equipe"});expect(change.mock.calls[0]?.[3]).toBe(change.mock.calls[1]?.[3])});
 it("fecha com Escape e restaura foco",async()=>{render(<UnitMembershipPanel client={make()} authorizedUnits={units}/>);const opener=await screen.findByRole("button",{name:"Revogar vínculo"});opener.focus();fireEvent.click(opener);fireEvent.keyDown(document,{key:"Escape"});expect(screen.queryByRole("dialog")).toBeNull();expect(document.activeElement).toBe(opener)});
 it("atualiza explicitamente o snapshot sem causar mutação",async()=>{const list=vi.fn(make().listUnitMemberships),change=vi.fn();render(<UnitMembershipPanel client={make({listUnitMemberships:list,changeUnitMembership:change})} authorizedUnits={units}/>);await screen.findByRole("listitem");fireEvent.click(screen.getByRole("button",{name:"Atualizar vínculos"}));await vi.waitFor(()=>expect(list).toHaveBeenCalledTimes(2));expect(change).not.toHaveBeenCalled()});
 it("purga unidade removida e nunca requisita a autorização antiga novamente",async()=>{const list=vi.fn(make().listUnitMemberships);const view=render(<UnitMembershipPanel client={make({listUnitMemberships:list})} authorizedUnits={units}/>);await screen.findByRole("listitem");list.mockClear();view.rerender(<UnitMembershipPanel client={make({listUnitMemberships:list})} authorizedUnits={[units[1]!]}/>);await vi.waitFor(()=>expect(list).toHaveBeenCalledWith({unitId:units[1]!.id,limit:25}));expect(list.mock.calls.some(([input])=>input.unitId===units[0]!.id)).toBe(false)});
 it.each([404,409])("reconcilia a lista e descarta intenção obsoleta após %s",async status=>{const changed={...member,version:5,status:"REVOKED" as const,allowedActions:["REACTIVATE" as const]};const list=vi.fn().mockResolvedValueOnce({items:[member]}).mockResolvedValueOnce({items:[changed]});const change=vi.fn().mockRejectedValueOnce(new ApiProblem({type:"about:blank",title:"Falha",status,correlationId:`corr-${status}`}));render(<UnitMembershipPanel client={make({listUnitMemberships:list,changeUnitMembership:change})} authorizedUnits={units}/>);fireEvent.click(await screen.findByRole("button",{name:"Revogar vínculo"}));fireEvent.change(screen.getByLabelText("Motivo"),{target:{value:"Atualização concorrente"}});fireEvent.click(screen.getByRole("button",{name:"Confirmar revogar vínculo"}));await vi.waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());expect((await screen.findByRole("status")).textContent).toContain("lista foi atualizada");expect(screen.getByRole("listitem").textContent).toContain("Revogado");expect(list).toHaveBeenCalledTimes(2)});
});
