import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { ApiProblem, AuthenticationRequired } from "@zap-pronto/api-client";

export type SlaPriority="LOW"|"NORMAL"|"HIGH"|"URGENT";
export type UnitSlaPolicy={readonly unitId:string;readonly version:number;readonly effectiveAt:string;readonly targets:readonly{readonly priority:SlaPriority;readonly targetMinutes:number}[];readonly replayed?:boolean};
export interface UnitSlaPolicyClient{
  getUnitSlaPolicy(unitId:string):Promise<UnitSlaPolicy|null>;
  setUnitSlaPolicy(unitId:string,input:{expectedVersion:number;targets:readonly{priority:SlaPriority;targetMinutes:number}[]},key:string):Promise<UnitSlaPolicy>;
}
export type SlaPolicyUnit={readonly id:string;readonly name:string};
const priorities:readonly{priority:SlaPriority;label:string}[]=[{priority:"LOW",label:"Prioridade baixa"},{priority:"NORMAL",label:"Prioridade normal"},{priority:"HIGH",label:"Prioridade alta"},{priority:"URGENT",label:"Prioridade urgente"}];
const emptyTargets=()=>({LOW:"",NORMAL:"",HIGH:"",URGENT:""} satisfies Record<SlaPriority,string>);

export function UnitSlaPolicyPanel({client,readableUnits,manageableUnitIds,onAuthenticationRequired=()=>undefined,onAuthorizationChanged=()=>undefined,onNavigationStateChange}:{readonly client:UnitSlaPolicyClient;readonly readableUnits:readonly SlaPolicyUnit[];readonly manageableUnitIds:readonly string[];readonly onAuthenticationRequired?:()=>void;readonly onAuthorizationChanged?:()=>void;readonly onNavigationStateChange?:(state:{blocked:boolean;dirty:boolean})=>void}){
  const[unitId,setUnitId]=useState(readableUnits[0]?.id??"");const[policy,setPolicy]=useState<UnitSlaPolicy|null>();const[targets,setTargets]=useState<Record<SlaPriority,string>>(emptyTargets);const[loading,setLoading]=useState(readableUnits.length>0);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();const[dialogOpen,setDialogOpen]=useState(false);const[key,setKey]=useState<string>();const[submitting,setSubmitting]=useState(false);const[mutationError,setMutationError]=useState<string>();
  const generation=useRef(0),mutationLock=useRef<symbol|undefined>(undefined),dialogRef=useRef<HTMLDivElement>(null),openerRef=useRef<HTMLElement|null>(null);
  function purge(){generation.current+=1;setPolicy(undefined);setTargets(emptyTargets());setLoading(false);setError(undefined);setNotice(undefined);setDialogOpen(false);setKey(undefined);setSubmitting(false);setMutationError(undefined);mutationLock.current=undefined}
  function accessFailure(cause:unknown){if(cause instanceof AuthenticationRequired||cause instanceof ApiProblem&&cause.problem.status===401){purge();onAuthenticationRequired();return true}if(cause instanceof ApiProblem&&cause.problem.status===403){purge();onAuthorizationChanged();return true}return false}
  function applyPolicy(value:UnitSlaPolicy|null){setPolicy(value);setTargets(value?Object.fromEntries(value.targets.map(target=>[target.priority,String(target.targetMinutes)]))as Record<SlaPriority,string>:emptyTargets())}
  async function load(selected=unitId){if(!readableUnits.some(unit=>unit.id===selected))return;const g=++generation.current;setLoading(true);setError(undefined);setNotice(undefined);try{const value=await client.getUnitSlaPolicy(selected);if(g!==generation.current||selected!==unitId)return;applyPolicy(value)}catch(cause){if(g!==generation.current)return;if(cause instanceof ApiProblem&&cause.problem.status===404)applyPolicy(null);else if(!accessFailure(cause))setError("Não foi possível carregar a política de SLA.")}finally{if(g===generation.current)setLoading(false)}}
  useLayoutEffect(()=>{if(unitId&&readableUnits.some(unit=>unit.id===unitId))return;const fallback=readableUnits[0]?.id??"";purge();setLoading(Boolean(fallback));setUnitId(fallback)},[readableUnits,unitId]);
  useEffect(()=>{if(unitId&&readableUnits.some(unit=>unit.id===unitId))void load(unitId);return()=>{generation.current+=1}},[client,unitId]);
  const canManage=manageableUnitIds.includes(unitId);
  const valid=priorities.every(({priority})=>/^\d+$/u.test(targets[priority])&&Number.isSafeInteger(Number(targets[priority]))&&Number(targets[priority])>0);
  const dirty=canManage&&(policy?priorities.some(({priority})=>String(policy.targets.find(target=>target.priority===priority)?.targetMinutes??"")!==targets[priority]):priorities.some(({priority})=>targets[priority]!==""));
  const navigationBlocked=dialogOpen||submitting;
  useEffect(()=>{onNavigationStateChange?.({blocked:navigationBlocked,dirty:dirty||navigationBlocked||Boolean(key)})},[onNavigationStateChange,navigationBlocked,dirty,key]);
  useEffect(()=>()=>onNavigationStateChange?.({blocked:false,dirty:false}),[onNavigationStateChange]);
  function changeUnit(value:string){if(value===unitId||navigationBlocked)return;if(dirty&&!window.confirm("Descartar as alterações não salvas da política de SLA?"))return;purge();setLoading(true);setUnitId(value)}
  function openConfirmation(){if(!valid||!dirty)return;openerRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialogOpen(true);setMutationError(undefined);setKey(undefined)}
  function close(){if(submitting)return;setDialogOpen(false);setMutationError(undefined);setKey(undefined)}
  useEffect(()=>{if(!dialogOpen)return;dialogRef.current?.querySelector<HTMLElement>("button:not([disabled])")?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!submitting){event.preventDefault();close()}};document.addEventListener("keydown",listener);return()=>document.removeEventListener("keydown",listener)},[dialogOpen,submitting]);
  useEffect(()=>{if(!dialogOpen&&openerRef.current){openerRef.current.focus();openerRef.current=null}},[dialogOpen]);
  async function confirm(){if(!dialogOpen||!valid||mutationLock.current)return;const token=Symbol("sla-policy");mutationLock.current=token;const g=generation.current,captured=unitId,retryKey=key??crypto.randomUUID();setKey(retryKey);setSubmitting(true);setMutationError(undefined);try{const value=await client.setUnitSlaPolicy(captured,{expectedVersion:policy?.version??0,targets:priorities.map(({priority})=>({priority,targetMinutes:Number(targets[priority])}))},retryKey);if(g!==generation.current||captured!==unitId)return;applyPolicy(value);setDialogOpen(false);setKey(undefined);setNotice("Política de SLA atualizada.")}catch(cause){if(g!==generation.current)return;if(accessFailure(cause))return;if(cause instanceof ApiProblem&&(cause.problem.status===404||cause.problem.status===409)){setDialogOpen(false);setKey(undefined);await load(captured);if(captured===unitId)setNotice(cause.problem.status===404?"A unidade ou política não está mais disponível. Os dados foram atualizados.":"A política foi alterada por outra pessoa. Os dados foram atualizados.")}else setMutationError("Não foi possível atualizar a política de SLA. Tente novamente.")}finally{if(mutationLock.current===token)mutationLock.current=undefined;if(g===generation.current)setSubmitting(false)}}
  return <section aria-labelledby="sla-policy-title"><div inert={dialogOpen?true:undefined} aria-hidden={dialogOpen?true:undefined}><h2 id="sla-policy-title">Política de SLA da unidade</h2>{readableUnits.length===0?<p>Nenhuma unidade autorizada.</p>:<><label>Unidade<select value={unitId} disabled={navigationBlocked} onChange={event=>changeUnit(event.target.value)}>{readableUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><button type="button" disabled={loading||navigationBlocked} onClick={()=>void load()}>Atualizar política</button></>}{notice&&<p role="status">{notice}</p>}{loading?<p>Carregando…</p>:error?<><p role="alert">{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></>:unitId&&<><p>{policy?`Política vigente desde ${new Date(policy.effectiveAt).toLocaleString("pt-BR")}. Versão ${policy.version}.`:"Nenhuma política de SLA configurada para esta unidade."}</p><p>Os prazos configurados serão aplicados somente a novos atendimentos e reaberturas. Atendimentos existentes não serão recalculados.</p>{canManage? <>{priorities.map(({priority,label})=><label key={priority}>{label} (minutos)<input type="number" inputMode="numeric" min="1" step="1" required value={targets[priority]} onChange={event=>{setTargets(current=>({...current,[priority]:event.target.value}));setKey(undefined);setMutationError(undefined);setNotice(undefined)}}/></label>)}<button type="button" disabled={!valid||!dirty||navigationBlocked} onClick={openConfirmation}>Salvar política de SLA</button></>:<dl>{priorities.map(({priority,label})=><div key={priority}><dt>{label}</dt><dd>{targets[priority]?`${targets[priority]} minutos`:"Não configurada"}</dd></div>)}</dl>}</>}</div>{dialogOpen&&<div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="sla-confirm-title"><h3 id="sla-confirm-title">Confirmar política de SLA</h3><p>Esta alteração valerá somente para novos atendimentos e reaberturas desta unidade.</p>{mutationError&&<p role="alert">{mutationError}</p>}<button type="button" disabled={submitting} onClick={()=>void confirm()}>{submitting?"Salvando…":"Confirmar alteração"}</button><button type="button" disabled={submitting} onClick={close}>Cancelar</button></div>}</section>;
}
