import type{FastifyInstance}from"fastify";import{AcknowledgeInboxSlaAlertParamsSchema,AcknowledgeInboxSlaAlertRequestSchema,AcknowledgeInboxSlaAlertResponseSchema,ListInboxSlaAlertsQuerySchema,ListInboxSlaAlertsResponseSchema,ProblemDetailsSchema,type AcknowledgeInboxSlaAlertRequest,type ListInboxSlaAlertsQuery}from"@zap-pronto/contracts";import type{TenantQueryClient,TenantTransactionPool}from"@zap-pronto/core/database/tenant-transaction";import{acknowledgeSlaAlert,listSlaAlerts,slaAlertAcknowledgementFingerprint}from"@zap-pronto/core";import{protectedRoute}from"../http/protected-route.js";
const problems={400:ProblemDetailsSchema,401:ProblemDetailsSchema,403:ProblemDetailsSchema,404:ProblemDetailsSchema,409:ProblemDetailsSchema,500:ProblemDetailsSchema,503:ProblemDetailsSchema}as const;
export class SlaAlertError extends Error{constructor(readonly statusCode:400|404|409,readonly code:string){super(code)}static from(error:unknown):never{if(error instanceof SlaAlertError)throw error;const code=error instanceof Error?error.message:"";if(["INVALID_PAGE_CURSOR","INVALID_SLA_ALERT_LIST_REQUEST","INVALID_SLA_ALERT_ACKNOWLEDGEMENT_REQUEST"].includes(code))throw new SlaAlertError(400,"INVALID_REQUEST");if(code==="SLA_ALERT_NOT_FOUND"||code==="SLA_ALERT_LIST_NOT_FOUND")throw new SlaAlertError(404,"RESOURCE_NOT_FOUND");if(code==="SLA_ALERT_ACKNOWLEDGEMENT_CONFLICT"||code==="SLA_ALERT_ACKNOWLEDGEMENT_IDEMPOTENCY_CONFLICT")throw new SlaAlertError(409,"SLA_ALERT_CONFLICT");throw error}}
function key(headers:Record<string,unknown>){const value=headers["idempotency-key"];if(typeof value!=="string"||value.trim()!==value||value.length<8||value.length>200)throw new SlaAlertError(400,"INVALID_REQUEST");return value}
async function unit(client:TenantQueryClient,handoffId:string,expectedVersion:number,idempotencyKey:string){const fingerprint=slaAlertAcknowledgementFingerprint({handoffId,expectedVersion}),result=await client.query('SELECT resolve_inbox_sla_alert_ack_unit($1,$2,$3,$4) AS "unitId"',[handoffId,expectedVersion,idempotencyKey,fingerprint])as{rows:{unitId:string|null}[]};const value=result.rows[0]?.unitId;if(!value)throw new SlaAlertError(404,"RESOURCE_NOT_FOUND");return value}
export function registerInboxSlaAlertRoutes(app:FastifyInstance,pool:TenantTransactionPool):void{
 app.get("/v1/inbox/sla-alerts",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"sla_alert.read",scope:{kind:"unit",async resolveUnitId(_c,r){return(r.query as ListInboxSlaAlertsQuery).unitId}}},schema:{operationId:"listInboxSlaAlerts",querystring:ListInboxSlaAlertsQuerySchema,response:{200:ListInboxSlaAlertsResponseSchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{const q=request.query as ListInboxSlaAlertsQuery,page=await listSlaAlerts(client,{unitId:q.unitId,...(q.limit!==undefined?{pageSize:q.limit}:{}),...(q.severity!==undefined?{slaStatus:q.severity}:{}),...(q.priority!==undefined?{priority:q.priority}:{}),...(q.cursor!==undefined?{cursor:q.cursor}:{})});return{items:page.items.map(row=>({handoffId:row.handoffId,unitId:row.unitId,priority:row.priority,severity:row.slaStatus,slaDueAt:row.slaDueAt?.toISOString()??null,queuedAt:row.queuedAt.toISOString(),ageSeconds:row.ageSeconds,availableCapacity:row.availableCapacity,acknowledgedAt:row.acknowledgedAt?.toISOString()??null,version:row.acknowledgementVersion})),...(page.nextCursor?{nextCursor:page.nextCursor}:{})}}catch(error){return SlaAlertError.from(error)}}}));
 app.post("/v1/inbox/sla-alerts/:handoffId/acknowledge",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"sla_alert.acknowledge",scope:{kind:"unit",async resolveUnitId(client,request){const handoffId=(request.params as{handoffId:string}).handoffId,expectedVersion=(request.body as AcknowledgeInboxSlaAlertRequest).expectedVersion;return unit(client,handoffId,expectedVersion,key(request.headers))}}},schema:{operationId:"acknowledgeInboxSlaAlert",params:AcknowledgeInboxSlaAlertParamsSchema,headers:{type:"object",required:["idempotency-key"],properties:{"idempotency-key":{type:"string",minLength:8,maxLength:200}}},body:AcknowledgeInboxSlaAlertRequestSchema,response:{200:AcknowledgeInboxSlaAlertResponseSchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{const handoffId=(request.params as{handoffId:string}).handoffId,body=request.body as AcknowledgeInboxSlaAlertRequest,row=await acknowledgeSlaAlert(client,{handoffId,expectedVersion:body.expectedVersion,idempotencyKey:key(request.headers)});if(!row)throw new Error("SLA_ALERT_NOT_FOUND");return{...row,acknowledgedAt:row.acknowledgedAt.toISOString()}}catch(error){return SlaAlertError.from(error)}}}));
}
