import type{FastifyInstance}from"fastify";
import{ProblemDetailsSchema,SetUnitOperationalTimezoneRequestSchema,SetUnitOperationalTimezoneResponseSchema,UnitOperationalTimezoneParamsSchema,UnitOperationalTimezoneSchema,type SetUnitOperationalTimezoneRequest,type UnitOperationalTimezone}from"@zap-pronto/contracts";
import type{TenantTransactionPool}from"@zap-pronto/core/database/tenant-transaction";
import{getUnitOperationalTimezone,setUnitOperationalTimezone,type UnitOperationalTimezone as DomainTimezone}from"@zap-pronto/core/domain/unit-operational-timezone";
import{protectedRoute}from"../http/protected-route.js";
const problems={400:ProblemDetailsSchema,401:ProblemDetailsSchema,403:ProblemDetailsSchema,404:ProblemDetailsSchema,409:ProblemDetailsSchema,500:ProblemDetailsSchema,503:ProblemDetailsSchema}as const;
function key(headers:Record<string,unknown>){const value=headers["idempotency-key"];if(typeof value!=="string"||value.trim()!==value||value.length<8||value.length>200)throw new UnitOperationalTimezoneError(400,"INVALID_REQUEST");return value}
function view(row:DomainTimezone):UnitOperationalTimezone{return{unitId:row.unitId,timeZone:row.timeZone,version:row.version,updatedAt:row.updatedAt.toISOString()}}
export class UnitOperationalTimezoneError extends Error{constructor(readonly statusCode:400|404|409,readonly code:string){super(code)}static from(error:unknown):never{if(error instanceof UnitOperationalTimezoneError)throw error;const code=error instanceof Error?error.message:"";if(code==="INVALID_UNIT_OPERATIONAL_TIMEZONE_REQUEST")throw new UnitOperationalTimezoneError(400,"INVALID_REQUEST");if(code==="UNIT_OPERATIONAL_TIMEZONE_NOT_FOUND")throw new UnitOperationalTimezoneError(404,"RESOURCE_NOT_FOUND");if(code==="UNIT_OPERATIONAL_TIMEZONE_CONFLICT"||code==="UNIT_OPERATIONAL_TIMEZONE_IDEMPOTENCY_CONFLICT")throw new UnitOperationalTimezoneError(409,"UNIT_OPERATIONAL_TIMEZONE_CONFLICT");throw error}}
export function registerUnitOperationalTimezoneRoutes(app:FastifyInstance,pool:TenantTransactionPool):void{
 const scope={kind:"unit"as const,async resolveUnitId(_client:unknown,request:{params:unknown}){return(request.params as{unitId:string}).unitId}};
 app.get("/v1/units/:unitId/operational-timezone",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"unit_timezone.read",scope},schema:{operationId:"getUnitOperationalTimezone",params:UnitOperationalTimezoneParamsSchema,response:{200:UnitOperationalTimezoneSchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{return view(await getUnitOperationalTimezone(client,(request.params as{unitId:string}).unitId))}catch(error){return UnitOperationalTimezoneError.from(error)}}}));
 app.post("/v1/units/:unitId/operational-timezone",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"unit_timezone.manage",scope},schema:{operationId:"setUnitOperationalTimezone",params:UnitOperationalTimezoneParamsSchema,headers:{type:"object",required:["idempotency-key"],properties:{"idempotency-key":{type:"string",minLength:8,maxLength:200}}},body:SetUnitOperationalTimezoneRequestSchema,response:{200:SetUnitOperationalTimezoneResponseSchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{const unitId=(request.params as{unitId:string}).unitId,body=request.body as SetUnitOperationalTimezoneRequest,row=await setUnitOperationalTimezone(client,{unitId,timeZone:body.timeZone,expectedVersion:body.expectedVersion,idempotencyKey:key(request.headers)});return{...view(row),replayed:Boolean(row.replayed)}}catch(error){return UnitOperationalTimezoneError.from(error)}}}));
}
