import type{FastifyInstance}from"fastify";import{ProblemDetailsSchema,SetUnitAssignmentPolicyRequestSchema,SetUnitAssignmentPolicyResponseSchema,UnitAssignmentPolicyParamsSchema,UnitAssignmentPolicySchema,type SetUnitAssignmentPolicyRequest,type UnitAssignmentPolicy}from"@zap-pronto/contracts";
import type{TenantTransactionPool}from"@zap-pronto/core/database/tenant-transaction";import{getUnitAssignmentPolicy,setUnitAssignmentPolicy,type AssignmentPolicyRecord,type UnitAssignmentPolicy as DomainPolicy}from"@zap-pronto/core/domain/assignment-policy";import{protectedRoute}from"../http/protected-route.js";
const problems={400:ProblemDetailsSchema,401:ProblemDetailsSchema,403:ProblemDetailsSchema,404:ProblemDetailsSchema,409:ProblemDetailsSchema,500:ProblemDetailsSchema,503:ProblemDetailsSchema}as const;
function key(headers:Record<string,unknown>){const value=headers["idempotency-key"];if(typeof value!=="string"||value.trim()!==value||value.length<8||value.length>200)throw new AssignmentPolicyError(400,"INVALID_REQUEST");return value}
function base(row:AssignmentPolicyRecord){return{unitId:row.unitId,mode:row.mode,version:row.version,updatedAt:row.updatedAt.toISOString()}}
function view(row:DomainPolicy):UnitAssignmentPolicy{return{...base(row),readiness:row.readiness}}
export class AssignmentPolicyError extends Error{constructor(readonly statusCode:400|404|409,readonly code:string){super(code)}static from(error:unknown):never{if(error instanceof AssignmentPolicyError)throw error;const code=error instanceof Error?error.message:"";
  if(code==="INVALID_ASSIGNMENT_POLICY_REQUEST")throw new AssignmentPolicyError(400,"INVALID_REQUEST");if(code==="ASSIGNMENT_POLICY_NOT_FOUND")throw new AssignmentPolicyError(404,"RESOURCE_NOT_FOUND");
  if(code==="ASSIGNMENT_POLICY_NOT_READY")throw new AssignmentPolicyError(409,"SHIFT_ENFORCEMENT_NOT_READY");if(code==="ASSIGNMENT_POLICY_CONFLICT"||code==="ASSIGNMENT_POLICY_IDEMPOTENCY_CONFLICT")throw new AssignmentPolicyError(409,"ASSIGNMENT_POLICY_CONFLICT");throw error}}
export function registerUnitAssignmentPolicyRoutes(app:FastifyInstance,pool:TenantTransactionPool):void{const scope={kind:"unit"as const,async resolveUnitId(_client:unknown,request:{params:unknown}){return(request.params as{unitId:string}).unitId}};
  app.get("/v1/units/:unitId/assignment-policy",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"shift.read",scope},schema:{operationId:"getUnitAssignmentPolicy",params:UnitAssignmentPolicyParamsSchema,response:{200:UnitAssignmentPolicySchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{return view(await getUnitAssignmentPolicy(client,(request.params as{unitId:string}).unitId))}catch(error){return AssignmentPolicyError.from(error)}}}));
  app.post("/v1/units/:unitId/assignment-policy",protectedRoute({pool,noStore:true,authorization:{kind:"permission",permission:"shift.manage",scope},schema:{operationId:"setUnitAssignmentPolicy",params:UnitAssignmentPolicyParamsSchema,headers:{type:"object",required:["idempotency-key"],properties:{"idempotency-key":{type:"string",minLength:8,maxLength:200}}},body:SetUnitAssignmentPolicyRequestSchema,response:{200:SetUnitAssignmentPolicyResponseSchema,...problems}},async handler(client,request,reply){void reply.header("cache-control","no-store");try{const body=request.body as SetUnitAssignmentPolicyRequest,row=await setUnitAssignmentPolicy(client,{unitId:(request.params as{unitId:string}).unitId,mode:body.mode,expectedVersion:body.expectedVersion,idempotencyKey:key(request.headers)});return{...base(row),replayed:row.replayed}}catch(error){return AssignmentPolicyError.from(error)}}}))}
