import assert from "node:assert/strict";
import test from "node:test";
import { buildApp } from "./app.js";
import { IdentityTokenRejectedError } from "./auth/errors.js";
import { parseBearerAuthorization } from "./auth/bearer.js";
import { getRegisteredRoutePolicies, publicEndpointInventory } from "./auth/plugin.js";
import { protectedRoute } from "./http/protected-route.js";
import type {
  TenantTransactionConnection,
  TenantTransactionPool,
} from "@zap-pronto/core/database/tenant-transaction";

function authorizationPool(options: { resolved?: boolean; allowed?: boolean } = {}): {
  pool: TenantTransactionPool;
  queries: string[];
} {
  const queries: string[] = [];
  const connection: TenantTransactionConnection = {
    async query(sql) {
      queries.push(sql.replace(/\s+/g, " ").trim());
      if (sql.includes("resolve_oidc_principal")) {
        return options.resolved === false ? { rows: [] } : {
          rows: [{
            tenant_id: "11111111-1111-4111-8111-111111111111",
            user_id: "22222222-2222-4222-8222-222222222222",
          }],
        };
      }
      if (sql.includes("current_actor_has_permission")) {
        return { rows: [{ allowed: options.allowed !== false }] };
      }
      return { rows: [] };
    },
    release() {},
  };
  return { pool: { async connect() { return connection; } }, queries };
}

function currentUserPool(options: { assigned?: boolean; rateAllowed?: boolean } = {}): TenantTransactionPool {
  return { async connect() {
    return {
      async query(sql) {
        if (sql.includes("consume_invitation_acceptance_rate_limit")) return { rowCount: 1, rows: [{
          allowed: options.rateAllowed !== false, remaining: options.rateAllowed === false ? 0 : 4,
          retry_after_seconds: 37, reset_at: new Date(Date.now() + 37_000),
        }] };
        if (sql.includes("accept_user_invitation_oidc")) return { rowCount: 1, rows: [{ replayed: false }] };
        if (sql.includes("resolve_oidc_principal")) return { rows: [{
          tenant_id: "11111111-1111-4111-8111-111111111111",
          user_id: "22222222-2222-4222-8222-222222222222",
        }] };
        if (sql.includes("account.id AS user_id")) return { rows: [{
          user_id: "22222222-2222-4222-8222-222222222222", email: "agent@example.test",
          display_name: "Agente", tenant_id: "11111111-1111-4111-8111-111111111111",
          tenant_name: "Clínica",
        }] };
        if (sql.includes("unit.id AS unit_id")) return { rows: options.assigned === false ? [] : [{
          unit_id: "33333333-3333-4333-8333-333333333333", unit_code: "CENTRO",
          unit_name: "Centro", role: "ATTENDANT",
        }] };
        if (sql.includes("role_permission.permission_code")) return { rows: [{
          permission: "handoff.read", scope: "UNIT", unit_id: "33333333-3333-4333-8333-333333333333",
        }] };
        return { rows: [] };
      },
      release() {},
    };
  } };
}

test("health contract and OpenAPI are generated by the same schemas", async () => {
  const app = await buildApp();
  const response = await app.inject({ method: "GET", url: "/health/live" });
  assert.equal(response.statusCode, 200);
  assert.deepEqual(response.json(), { status: "ok" });
  assert.match(String(response.headers["x-correlation-id"]), /^[0-9a-f-]{36}$/);
  const document = app.swagger();
  assert.ok(document.paths?.["/health/live"]);
  assert.ok(document.paths?.["/health/ready"]);
  assert.ok(document.paths?.["/v1/me"]);
  assert.equal(document.paths?.["/health/live"]?.get?.operationId, "getHealthLive");
  const readinessUnavailable = document.paths?.["/health/ready"]?.get?.responses?.["503"] as
    { content?: Record<string, unknown> } | undefined;
  assert.ok(readinessUnavailable?.content?.["application/problem+json"]);
  assert.equal(readinessUnavailable?.content?.["application/json"], undefined);
  assert.match(JSON.stringify(document), /bearerAuth/);
  const injected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "trusted-correlation-123" } });
  assert.equal(injected.headers["x-correlation-id"], "trusted-correlation-123");
  const rejected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "invalid id with spaces" } });
  assert.notEqual(rejected.headers["x-correlation-id"], "invalid id with spaces");
  await app.close();
});

test("readiness checks the database and fails closed without exposing its error", async () => {
  const queries: string[] = [];
  let releases = 0;
  const ready = await buildApp({ pool: { async connect() { return {
    async query(sql) { queries.push(sql); return { rows: [{ "?column?": 1 }] }; },
    release() { releases += 1; },
  }; } } });
  const healthy = await ready.inject({ method: "GET", url: "/health/ready" });
  assert.equal(healthy.statusCode, 200);
  assert.deepEqual(healthy.json(), { status: "ok" });
  assert.deepEqual(queries, ["SELECT 1"]);
  assert.equal(releases, 1);
  await ready.close();

  const unavailable = await buildApp({ pool: { async connect() { throw new Error("secret database detail"); } } });
  const failed = await unavailable.inject({ method: "GET", url: "/health/ready" });
  assert.equal(failed.statusCode, 503);
  assert.equal(failed.headers["content-type"], "application/problem+json; charset=utf-8");
  assert.deepEqual(failed.json(), {
    type: "urn:zap-pronto:error:service-unavailable", title: "Service Unavailable", status: 503,
    detail: "The service is not ready", correlationId: failed.headers["x-correlation-id"],
  });
  assert.doesNotMatch(failed.body, /secret database detail/);
  await unavailable.close();
});

test("every versioned route has an explicit policy, scope and coherent error contract", async () => {
  const app = await buildApp(); await app.ready();
  const policies = getRegisteredRoutePolicies(app).filter(({ method }) => method !== "HEAD")
    .map(({ method, url, policy, permission, scope }) => [method, url, policy, permission ?? null, scope ?? null]);
  assert.deepEqual(policies.sort((left, right) => String(left).localeCompare(String(right))), [
    ["GET", "/v1/me", "bootstrap", null, null],
    ["GET", "/v1/users", "permission", "tenant.users.manage", "tenant"],
    ["GET", "/v1/users/invitations", "permission", "tenant.users.manage", "tenant"],
    ["GET", "/v1/users/invitations/options", "permission", "tenant.users.manage", "tenant"],
    ["POST", "/v1/auth/invitations/accept", "preProvisioning", null, null],
    ["POST", "/v1/users/:userId/status", "permission", "tenant.users.manage", "tenant"],
    ["POST", "/v1/users/invitations", "permission", "tenant.users.manage", "tenant"],
    ["POST", "/v1/users/invitations/:invitationId/reissue", "permission", "tenant.users.manage", "tenant"],
    ["POST", "/v1/users/invitations/:invitationId/revoke", "permission", "tenant.users.manage", "tenant"],
  ].sort((left, right) => String(left).localeCompare(String(right))));
  const document = app.swagger() as { paths: Record<string, Record<string, { responses?: Record<string, unknown> }>> };
  const expectedErrors: Record<string, readonly number[]> = {
    "GET /v1/me": [401, 403], "GET /v1/users": [400, 401, 403],
    "GET /v1/users/invitations": [400, 401, 403],
    "GET /v1/users/invitations/options": [401, 403],
    "POST /v1/users/invitations": [400, 401, 403, 404, 409],
    "POST /v1/users/:userId/status": [400, 401, 403, 404, 409],
    "POST /v1/users/invitations/:invitationId/revoke": [400, 401, 403, 404, 409],
    "POST /v1/users/invitations/:invitationId/reissue": [400, 401, 403, 404, 409],
    "POST /v1/auth/invitations/accept": [400, 401, 403, 409, 429],
  };
  for (const [key, statuses] of Object.entries(expectedErrors)) {
    const [method, routeUrl] = key.split(" ") as [string, string];
    const openApiUrl = routeUrl.replaceAll(":userId", "{userId}").replaceAll(":invitationId", "{invitationId}");
    const responses = document.paths[openApiUrl]?.[method.toLowerCase()]?.responses ?? {};
    for (const status of statuses) assert.ok(String(status) in responses, `${key}:MISSING_${status}`);
  }
  await app.close();
});

test("tenant-scoped target lookup returns a generic 404 without cross-tenant existence detail", async () => {
  const connection: TenantTransactionConnection = { async query(sql) {
    if (sql.includes("resolve_oidc_principal")) return { rows: [{ tenant_id: "11111111-1111-4111-8111-111111111111",
      user_id: "22222222-2222-4222-8222-222222222222" }] };
    if (sql.includes("current_actor_has_permission")) return { rows: [{ allowed: true }] };
    if (sql.includes("admin_change_user_status")) throw new Error("USER_NOT_FOUND");
    return { rows: [] };
  }, release() {} };
  const app = await buildApp({ pool: { async connect() { return connection; } }, identityVerifier: {
    async verifyBearer() { return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "admin" }; },
  } });
  const response = await app.inject({ method: "POST",
    url: "/v1/users/99999999-9999-4999-8999-999999999999/status", headers: {
      authorization: "Bearer accepted", "idempotency-key": "idor-command-1" },
    payload: { action: "BLOCK", expectedVersion: 1, reason: "Security review" } });
  assert.equal(response.statusCode, 404);
  assert.equal(response.json().type, "urn:zap-pronto:error:resource-not-found");
  assert.equal(response.json().detail, "RESOURCE_NOT_FOUND");
  assert.doesNotMatch(JSON.stringify(response.json()), /USER_NOT_FOUND|tenant/i);
  await app.close();
});

test("administrative invitation creation returns a one-time token and replay omits it", async () => {
  let replayed = false;
  const connection: TenantTransactionConnection = { async query(sql) {
    if (sql.includes("resolve_oidc_principal")) return { rows: [{ tenant_id: "11111111-1111-4111-8111-111111111111",
      user_id: "22222222-2222-4222-8222-222222222222" }] };
    if (sql.includes("current_actor_has_permission")) return { rows: [{ allowed: true }] };
    if (sql.includes("SELECT code FROM oidc_providers")) return { rows: [{ code: "primary" }] };
    if (sql.includes("SELECT id,code,name FROM units")) return { rows: [{ id: "33333333-3333-4333-8333-333333333333",
      code: "CENTRO", name: "Centro" }] };
    if (sql.includes("admin_create_user_invitation")) return { rowCount: 1, rows: [{
      id: "44444444-4444-4444-8444-444444444444", email: "user@example.test", display_name: "User",
      status: "PENDING", expires_at: "2026-08-20T12:00:00.000Z", oidc_provider_code: "primary",
      assignments: [{ unitId: "33333333-3333-4333-8333-333333333333", unitCode: "CENTRO",
        unitName: "Centro", role: "ATTENDANT" }], replayed }] };
    if (sql.includes("WITH admin_count")) return { rows: [{ id: "55555555-5555-4555-8555-555555555555",
      email: "staff@example.test", display_name: "Staff", status: "ACTIVE", version: 2,
      memberships: [], is_self: false, is_last_admin: false }] };
    if (sql.includes("WITH anchor AS") && sql.includes("user_invitations")) return { rows: [] };
    if (sql.includes("admin_change_user_status")) return { rowCount: 1, rows: [{
      user_id: "55555555-5555-4555-8555-555555555555", status: "BLOCKED", version: 3, replayed: false }] };
    if (sql.includes("admin_revoke_user_invitation")) return { rowCount: 1, rows: [{
      id: "44444444-4444-4444-8444-444444444444", email: "user@example.test", display_name: "User",
      status: "REVOKED", expires_at: "2026-08-20T12:00:00.000Z", oidc_provider_code: "primary",
      assignments: [], replayed: false }] };
    if (sql.includes("admin_reissue_user_invitation")) return { rowCount: 1, rows: [{
      id: "66666666-6666-4666-8666-666666666666", email: "user@example.test", display_name: "User",
      status: "PENDING", expires_at: "2026-08-21T12:00:00.000Z", oidc_provider_code: "primary",
      assignments: [], replayed: false }] };
    return { rows: [] };
  }, release() {} };
  const app = await buildApp({ pool: { async connect() { return connection; } }, identityVerifier: {
    async verifyBearer() { return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "admin" }; },
  } });
  const options = await app.inject({ method: "GET", url: "/v1/users/invitations/options",
    headers: { authorization: "Bearer accepted" } });
  assert.equal(options.statusCode, 200);
  assert.deepEqual(options.json().roles, ["UNIT_MANAGER", "SUPERVISOR", "ATTENDANT", "AUDITOR"]);
  const payload = { email: "user@example.test", displayName: "User", providerCode: "primary",
    expiresAt: "2026-08-20T12:00:00.000Z", assignments: [{
      unitId: "33333333-3333-4333-8333-333333333333", role: "ATTENDANT" }] };
  const invalid = await app.inject({ method: "POST", url: "/v1/users/invitations",
    headers: { authorization: "Bearer accepted" }, payload });
  assert.equal(invalid.statusCode, 400);
  assert.equal(invalid.json().type, "urn:zap-pronto:error:invalid-request");
  const created = await app.inject({ method: "POST", url: "/v1/users/invitations", headers: {
    authorization: "Bearer accepted", "idempotency-key": "invitation-command-1" }, payload });
  assert.equal(created.statusCode, 201);
  assert.equal(created.json().invitationToken.length, 43);
  replayed = true;
  const replay = await app.inject({ method: "POST", url: "/v1/users/invitations", headers: {
    authorization: "Bearer accepted", "idempotency-key": "invitation-command-1" }, payload });
  assert.equal(replay.statusCode, 200);
  assert.equal("invitationToken" in replay.json(), false);
  const users = await app.inject({ method: "GET", url: "/v1/users?limit=25",
    headers: { authorization: "Bearer accepted" } });
  assert.equal(users.statusCode, 200); assert.deepEqual(users.json().items[0].allowedActions, ["BLOCK", "REVOKE"]);
  const invalidCursor = await app.inject({ method: "GET", url: "/v1/users?cursor=invalid",
    headers: { authorization: "Bearer accepted" } });
  assert.equal(invalidCursor.statusCode, 400);
  const statusChange = await app.inject({ method: "POST",
    url: "/v1/users/55555555-5555-4555-8555-555555555555/status", headers: {
      authorization: "Bearer accepted", "idempotency-key": "status-command-1" },
    payload: { action: "BLOCK", expectedVersion: 2, reason: "Security review" } });
  assert.equal(statusChange.statusCode, 200); assert.equal(statusChange.json().user.version, 3);
  const revoked = await app.inject({ method: "POST",
    url: "/v1/users/invitations/44444444-4444-4444-8444-444444444444/revoke", headers: {
      authorization: "Bearer accepted", "idempotency-key": "revoke-command-1" }, payload: { reason: "Reissue" } });
  assert.equal(revoked.statusCode, 200); assert.equal(revoked.json().invitation.status, "REVOKED");
  const reissued = await app.inject({ method: "POST",
    url: "/v1/users/invitations/44444444-4444-4444-8444-444444444444/reissue", headers: {
      authorization: "Bearer accepted", "idempotency-key": "reissue-command-1" },
    payload: { reason: "New expiry", expiresAt: "2026-08-21T12:00:00.000Z" } });
  assert.equal(reissued.statusCode, 201); assert.equal(reissued.json().invitationToken.length, 43);
  await app.close();
});

test("GET /v1/me returns only the server-derived current user and disables caching", async () => {
  const app = await buildApp({
    pool: currentUserPool(),
    identityVerifier: { async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    } },
  });
  const response = await app.inject({
    method: "GET", url: "/v1/me?tenantId=client&userId=other",
    headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 200);
  assert.equal(response.headers["cache-control"], "no-store");
  assert.deepEqual(response.json(), {
    user: { id: "22222222-2222-4222-8222-222222222222", email: "agent@example.test", displayName: "Agente" },
    tenant: { id: "11111111-1111-4111-8111-111111111111", name: "Clínica" },
    memberships: [{ unitId: "33333333-3333-4333-8333-333333333333", unitCode: "CENTRO",
      unitName: "Centro", role: "ATTENDANT" }],
    grants: [{ permission: "handoff.read", scope: "UNIT", unitId: "33333333-3333-4333-8333-333333333333" }],
  });
  await app.close();
});

test("invitation acceptance uses verified OIDC email and never accepts tenant or actor input", async () => {
  const app = await buildApp({ pool: currentUserPool(), identityVerifier: { async verifyBearer() {
    return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "new-subject",
      verifiedEmail: "agent@example.test" };
  } } });
  const response = await app.inject({ method: "POST", url: "/v1/auth/invitations/accept?tenantId=forged",
    headers: { authorization: "Bearer accepted", "idempotency-key": "accept-command-1" },
    payload: { invitationToken: "a".repeat(43) } });
  assert.equal(response.statusCode, 200);
  assert.equal(response.headers["cache-control"], "no-store");
  assert.equal(response.json().currentUser.tenant.id, "11111111-1111-4111-8111-111111111111");
  assert.equal(response.json().replayed, false);
  await app.close();
});

test("invitation acceptance rate limit commits first and returns 429 with Retry-After", async () => {
  const app = await buildApp({ pool: currentUserPool({ rateAllowed: false }), identityVerifier: { async verifyBearer() {
    return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "limited-subject",
      verifiedEmail: "agent@example.test" };
  } } });
  const response = await app.inject({ method: "POST", url: "/v1/auth/invitations/accept",
    headers: { authorization: "Bearer accepted", "idempotency-key": "accept-command-2" },
    payload: { invitationToken: "b".repeat(43) } });
  assert.equal(response.statusCode, 429);
  assert.equal(response.headers["retry-after"], "37");
  assert.equal(response.json().type, "urn:zap-pronto:error:rate-limit-exceeded");
  await app.close();
});

test("GET /v1/me denies an identity without an active unit assignment", async () => {
  const app = await buildApp({
    pool: currentUserPool({ assigned: false }),
    identityVerifier: { async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    } },
  });
  const response = await app.inject({
    method: "GET", url: "/v1/me", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 403);
  assert.equal(response.json().type, "urn:zap-pronto:error:account-not-assigned");
  await app.close();
});

test("strict Bearer parser rejects ambiguous or client-crafted identity material", () => {
  assert.equal(parseBearerAuthorization("Bearer opaque-token"), "opaque-token");
  for (const value of [undefined, "", "bearer token", "Bearer", "Bearer  token", "Bearer token extra", "Bearer a,b"]) {
    assert.throws(() => parseBearerAuthorization(value));
  }
});

test("all /v1 endpoints are deny-by-default and health is explicitly public", async () => {
  assert.deepEqual(publicEndpointInventory, [
    "GET /health/live", "HEAD /health/live", "GET /health/ready", "HEAD /health/ready",
  ]);
  const app = await buildApp();
  const missing = await app.inject({ method: "GET", url: "/v1/not-registered" });
  assert.equal(missing.statusCode, 401);
  assert.equal(missing.json().status, 401);
  const unavailable = await app.inject({
    method: "GET", url: "/v1/not-registered", headers: { authorization: "Bearer valid-shape" },
  });
  assert.equal(unavailable.statusCode, 503);
  assert.equal(unavailable.json().status, 503);
  const health = await app.inject({ method: "GET", url: "/health/live" });
  assert.equal(health.statusCode, 200);
  const readiness = await app.inject({ method: "GET", url: "/health/ready" });
  assert.equal(readiness.statusCode, 503);
  await app.close();
});

test("verifier is injected, rejection is 401 and verified identity is server-derived", async () => {
  const seen: string[] = [];
  const database = authorizationPool();
  const app = await buildApp({ identityVerifier: {
    async verifyBearer(token) {
      seen.push(token);
      if (token === "rejected") throw new IdentityTokenRejectedError();
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    authorization: { kind: "permission", permission: "handoff.read", scope: { kind: "tenant" } },
    async handler(_client, request) { return { identity: request.externalIdentity }; },
  }));
  const rejected = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer rejected" },
  });
  assert.equal(rejected.statusCode, 401);
  const accepted = await app.inject({
    method: "GET", url: "/v1/probe?tenantId=client-value&actorId=client-value",
    headers: { authorization: "Bearer accepted" },
  });
  assert.equal(accepted.statusCode, 200);
  assert.deepEqual(accepted.json().identity, {
    issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1",
  });
  assert.deepEqual(seen, ["rejected", "accepted"]);
  assert.ok(database.queries.some((query) => query.includes("resolve_oidc_principal")));
  assert.ok(database.queries.some((query) => query.includes("current_actor_has_permission")));
  assert.ok(database.queries.includes("COMMIT"));
  await app.close();
});

test("a resolved identity without the route permission is denied and rolled back", async () => {
  const database = authorizationPool({ allowed: false });
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    authorization: { kind: "permission", permission: "handoff.read", scope: { kind: "tenant" } },
    async handler() { return { shouldNotRun: true }; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 403);
  assert.equal(response.json().status, 403);
  assert.ok(database.queries.includes("ROLLBACK"));
  assert.ok(!database.queries.includes("COMMIT"));
  await app.close();
});

test("an external identity not mapped in the platform database is unauthorized", async () => {
  const database = authorizationPool({ resolved: false });
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "unknown" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    authorization: { kind: "permission", permission: "handoff.read", scope: { kind: "tenant" } },
    async handler() { return { shouldNotRun: true }; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 401);
  assert.equal(response.json().status, 401);
  assert.ok(database.queries.includes("ROLLBACK"));
  await app.close();
});

test("a versioned route without an authorization policy cannot be registered", async () => {
  const app = await buildApp();
  assert.throws(() => app.get("/v1/unsafe", async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/metadata-only", {
    config: { permission: "handoff.read" },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/forged", {
    config: { permission: "handoff.read", authorizationEnforced: true },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/ambiguous", {
    config: { public: true, permission: "handoff.read" },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_AMBIGUOUS/);
  await app.close();
});

test("a versioned endpoint cannot make itself public outside the executable allowlist", async () => {
  const app = await buildApp();
  assert.throws(() => app.get("/v1/public", {
    config: { public: true },
    schema: { security: [] },
  }, async () => ({ public: true })), /ROUTE_PUBLIC_NOT_ALLOWLISTED/);
  assert.throws(() => app.route({
    method: ["GET", "POST"],
    url: "/health/live",
    config: { public: true },
    handler: async () => ({ status: "ok" }),
  }), /ROUTE_PUBLIC_NOT_ALLOWLISTED/);
  await app.close();
});

test("a unit-scoped route fails closed when its resolver does not return a UUID", async () => {
  const database = authorizationPool();
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  let handlerCalled = false;
  app.get("/v1/unit-probe", protectedRoute({
    pool: database.pool,
    authorization: { kind: "permission", permission: "handoff.read", scope: {
      kind: "unit", async resolveUnitId() { return undefined as unknown as string; },
    } },
    async handler() { handlerCalled = true; return {}; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/unit-probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 403);
  assert.equal(handlerCalled, false);
  assert.ok(database.queries.includes("ROLLBACK"));
  assert.ok(!database.queries.some((query) => query.includes("current_actor_has_permission")));
  await app.close();
});
