import assert from "node:assert/strict";
import test from "node:test";
import { buildApp } from "./app.js";

test("health contract and OpenAPI are generated by the same schemas", async () => {
  const app = await buildApp();
  const response = await app.inject({ method: "GET", url: "/health/live" });
  assert.equal(response.statusCode, 200);
  assert.deepEqual(response.json(), { status: "ok" });
  assert.match(String(response.headers["x-correlation-id"]), /^[0-9a-f-]{36}$/);
  const document = app.swagger();
  assert.ok(document.paths?.["/health/live"]);
  assert.equal(document.paths?.["/health/live"]?.get?.operationId, "getHealthLive");
  assert.match(JSON.stringify(document), /bearerAuth/);
  const injected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "trusted-correlation-123" } });
  assert.equal(injected.headers["x-correlation-id"], "trusted-correlation-123");
  const rejected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "invalid id with spaces" } });
  assert.notEqual(rejected.headers["x-correlation-id"], "invalid id with spaces");
  await app.close();
});
