import assert from "node:assert/strict";
import test from "node:test";
import { buildApp } from "./app.js";
import { IdentityTokenRejectedError } from "./auth/errors.js";
import { parseBearerAuthorization } from "./auth/bearer.js";
import { publicEndpointInventory } from "./auth/plugin.js";
import { protectedRoute } from "./http/protected-route.js";
import type {
  TenantTransactionConnection,
  TenantTransactionPool,
} from "@zap-pronto/core/database/tenant-transaction";

function authorizationPool(options: { resolved?: boolean; allowed?: boolean } = {}): {
  pool: TenantTransactionPool;
  queries: string[];
} {
  const queries: string[] = [];
  const connection: TenantTransactionConnection = {
    async query(sql) {
      queries.push(sql.replace(/\s+/g, " ").trim());
      if (sql.includes("resolve_oidc_principal")) {
        return options.resolved === false ? { rows: [] } : {
          rows: [{
            tenant_id: "11111111-1111-4111-8111-111111111111",
            user_id: "22222222-2222-4222-8222-222222222222",
          }],
        };
      }
      if (sql.includes("current_actor_has_permission")) {
        return { rows: [{ allowed: options.allowed !== false }] };
      }
      return { rows: [] };
    },
    release() {},
  };
  return { pool: { async connect() { return connection; } }, queries };
}

test("health contract and OpenAPI are generated by the same schemas", async () => {
  const app = await buildApp();
  const response = await app.inject({ method: "GET", url: "/health/live" });
  assert.equal(response.statusCode, 200);
  assert.deepEqual(response.json(), { status: "ok" });
  assert.match(String(response.headers["x-correlation-id"]), /^[0-9a-f-]{36}$/);
  const document = app.swagger();
  assert.ok(document.paths?.["/health/live"]);
  assert.equal(document.paths?.["/health/live"]?.get?.operationId, "getHealthLive");
  assert.match(JSON.stringify(document), /bearerAuth/);
  const injected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "trusted-correlation-123" } });
  assert.equal(injected.headers["x-correlation-id"], "trusted-correlation-123");
  const rejected = await app.inject({ method: "GET", url: "/health/live",
    headers: { "x-correlation-id": "invalid id with spaces" } });
  assert.notEqual(rejected.headers["x-correlation-id"], "invalid id with spaces");
  await app.close();
});

test("strict Bearer parser rejects ambiguous or client-crafted identity material", () => {
  assert.equal(parseBearerAuthorization("Bearer opaque-token"), "opaque-token");
  for (const value of [undefined, "", "bearer token", "Bearer", "Bearer  token", "Bearer token extra", "Bearer a,b"]) {
    assert.throws(() => parseBearerAuthorization(value));
  }
});

test("all /v1 endpoints are deny-by-default and health is explicitly public", async () => {
  assert.deepEqual(publicEndpointInventory, ["GET /health/live", "HEAD /health/live"]);
  const app = await buildApp();
  const missing = await app.inject({ method: "GET", url: "/v1/not-registered" });
  assert.equal(missing.statusCode, 401);
  assert.equal(missing.json().status, 401);
  const unavailable = await app.inject({
    method: "GET", url: "/v1/not-registered", headers: { authorization: "Bearer valid-shape" },
  });
  assert.equal(unavailable.statusCode, 503);
  assert.equal(unavailable.json().status, 503);
  const health = await app.inject({ method: "GET", url: "/health/live" });
  assert.equal(health.statusCode, 200);
  await app.close();
});

test("verifier is injected, rejection is 401 and verified identity is server-derived", async () => {
  const seen: string[] = [];
  const database = authorizationPool();
  const app = await buildApp({ identityVerifier: {
    async verifyBearer(token) {
      seen.push(token);
      if (token === "rejected") throw new IdentityTokenRejectedError();
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    permission: "handoff.read",
    scope: { kind: "tenant" },
    async handler(_client, request) { return { identity: request.externalIdentity }; },
  }));
  const rejected = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer rejected" },
  });
  assert.equal(rejected.statusCode, 401);
  const accepted = await app.inject({
    method: "GET", url: "/v1/probe?tenantId=client-value&actorId=client-value",
    headers: { authorization: "Bearer accepted" },
  });
  assert.equal(accepted.statusCode, 200);
  assert.deepEqual(accepted.json().identity, {
    issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1",
  });
  assert.deepEqual(seen, ["rejected", "accepted"]);
  assert.ok(database.queries.some((query) => query.includes("resolve_oidc_principal")));
  assert.ok(database.queries.some((query) => query.includes("current_actor_has_permission")));
  assert.ok(database.queries.includes("COMMIT"));
  await app.close();
});

test("a resolved identity without the route permission is denied and rolled back", async () => {
  const database = authorizationPool({ allowed: false });
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    permission: "handoff.read",
    scope: { kind: "tenant" },
    async handler() { return { shouldNotRun: true }; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 403);
  assert.equal(response.json().status, 403);
  assert.ok(database.queries.includes("ROLLBACK"));
  assert.ok(!database.queries.includes("COMMIT"));
  await app.close();
});

test("an external identity not mapped in the platform database is unauthorized", async () => {
  const database = authorizationPool({ resolved: false });
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "unknown" };
    },
  } });
  app.get("/v1/probe", protectedRoute({
    pool: database.pool,
    permission: "handoff.read",
    scope: { kind: "tenant" },
    async handler() { return { shouldNotRun: true }; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 401);
  assert.equal(response.json().status, 401);
  assert.ok(database.queries.includes("ROLLBACK"));
  await app.close();
});

test("a versioned route without an authorization policy cannot be registered", async () => {
  const app = await buildApp();
  assert.throws(() => app.get("/v1/unsafe", async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/metadata-only", {
    config: { permission: "handoff.read" },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/forged", {
    config: { permission: "handoff.read", authorizationEnforced: true },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_REQUIRED/);
  assert.throws(() => app.get("/v1/ambiguous", {
    config: { public: true, permission: "handoff.read" },
  }, async () => ({})), /ROUTE_AUTHORIZATION_POLICY_AMBIGUOUS/);
  await app.close();
});

test("a versioned endpoint cannot make itself public outside the executable allowlist", async () => {
  const app = await buildApp();
  assert.throws(() => app.get("/v1/public", {
    config: { public: true },
    schema: { security: [] },
  }, async () => ({ public: true })), /ROUTE_PUBLIC_NOT_ALLOWLISTED/);
  assert.throws(() => app.route({
    method: ["GET", "POST"],
    url: "/health/live",
    config: { public: true },
    handler: async () => ({ status: "ok" }),
  }), /ROUTE_PUBLIC_NOT_ALLOWLISTED/);
  await app.close();
});

test("a unit-scoped route fails closed when its resolver does not return a UUID", async () => {
  const database = authorizationPool();
  const app = await buildApp({ identityVerifier: {
    async verifyBearer() {
      return { issuer: "https://issuer.example", audience: "zap-pronto", subject: "subject-1" };
    },
  } });
  let handlerCalled = false;
  app.get("/v1/unit-probe", protectedRoute({
    pool: database.pool,
    permission: "handoff.read",
    scope: {
      kind: "unit",
      async resolveUnitId() { return undefined as unknown as string; },
    },
    async handler() { handlerCalled = true; return {}; },
  }));
  const response = await app.inject({
    method: "GET", url: "/v1/unit-probe", headers: { authorization: "Bearer accepted" },
  });
  assert.equal(response.statusCode, 403);
  assert.equal(handlerCalled, false);
  assert.ok(database.queries.includes("ROLLBACK"));
  assert.ok(!database.queries.some((query) => query.includes("current_actor_has_permission")));
  await app.close();
});
